In [3]:
!pip install numpy

Defaulting to user installation because normal site-packages is not writeable


In [5]:
import numpy as np

# 1. Create

In [11]:
data = np.random.rand(2,3,4)
zeroes = np.zeros((2,2,2))
full = np.full((2,2,2), 7)
ones = np.ones((2,2,2))

In [12]:
data

array([[[0.19415597, 0.41220146, 0.82525834, 0.1630201 ],
        [0.68669742, 0.65632551, 0.9912395 , 0.00110359],
        [0.60119661, 0.92870434, 0.29351993, 0.70496092]],

       [[0.41713171, 0.32231215, 0.83992331, 0.7242938 ],
        [0.89666796, 0.83728212, 0.92357801, 0.50269103],
        [0.95616948, 0.24889797, 0.77030681, 0.08384539]]])

In [14]:
zeroes

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [15]:
full

array([[[7, 7],
        [7, 7]],

       [[7, 7],
        [7, 7]]])

In [16]:
ones

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [18]:
arr = np.array([[1,2,3,4],[1,2,3,4]])

In [19]:
arr

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

In [20]:
type(arr)

numpy.ndarray

# 2. READ  

In [22]:
# Attributes
shape = data.shape
size = data.size
types = data.dtype

In [23]:
shape

(2, 3, 4)

In [24]:
size

24

In [26]:
types

dtype('float64')

In [30]:
#slicing
arr= data[0]
slicer = data[0:2]
reverse = data[-1]
singleval = data[0][0][0]

In [31]:
arr

array([[0.19415597, 0.41220146, 0.82525834, 0.1630201 ],
       [0.68669742, 0.65632551, 0.9912395 , 0.00110359],
       [0.60119661, 0.92870434, 0.29351993, 0.70496092]])

In [32]:
slicer

array([[[0.19415597, 0.41220146, 0.82525834, 0.1630201 ],
        [0.68669742, 0.65632551, 0.9912395 , 0.00110359],
        [0.60119661, 0.92870434, 0.29351993, 0.70496092]],

       [[0.41713171, 0.32231215, 0.83992331, 0.7242938 ],
        [0.89666796, 0.83728212, 0.92357801, 0.50269103],
        [0.95616948, 0.24889797, 0.77030681, 0.08384539]]])

In [33]:
reverse

array([[0.41713171, 0.32231215, 0.83992331, 0.7242938 ],
       [0.89666796, 0.83728212, 0.92357801, 0.50269103],
       [0.95616948, 0.24889797, 0.77030681, 0.08384539]])

In [34]:
singleval

np.float64(0.19415597165950094)

# 3. Update

In [35]:
list1 = np.random.rand(10)
list2 = np.random.rand(10)

In [36]:
list1

array([0.76813934, 0.75155836, 0.57975727, 0.45763566, 0.9076794 ,
       0.13867953, 0.85008162, 0.61795888, 0.80792449, 0.75543656])

In [37]:
list2

array([0.0533391 , 0.52317013, 0.00717002, 0.22804007, 0.22204314,
       0.42706448, 0.08898145, 0.3761066 , 0.32946093, 0.85233622])

In [39]:
#Basic Math
add = np.add(list1, list2)
sub = np.subtract(list1,list2)
div = np.divide(list1,list2)
mult = np.multiply(list1,list2)
dot = np.dot(list1,list2)

In [40]:
add

array([0.82147844, 1.27472848, 0.58692729, 0.68567572, 1.12972254,
       0.56574402, 0.93906308, 0.99406549, 1.13738543, 1.60777279])

In [41]:
sub

array([ 0.71480023,  0.22838823,  0.57258724,  0.22959559,  0.68563626,
       -0.28838495,  0.76110017,  0.24185228,  0.47846356, -0.09689966])

In [42]:
div

array([14.40105455,  1.43654678, 80.85847355,  2.00682127,  4.08785156,
        0.32472739,  9.55346975,  1.64304183,  2.45226192,  0.88631287])

In [43]:
mult

array([0.04097186, 0.39319288, 0.00415687, 0.10435927, 0.20154398,
       0.0592251 , 0.0756415 , 0.23241842, 0.26617956, 0.64388595])

In [44]:
dot

np.float64(2.0215753897720345)

In [46]:
# Stat functions
sqrt = np.sqrt(25)
ab = np.abs(-2)
power = np.power(2,7)
log = np.log(25)
exp = ([2,3])
mins = np.min(list1)
maxs = np.max(list1)

In [47]:
sqrt

np.float64(5.0)

In [48]:
ab

np.int64(2)

In [49]:
power

np.int64(128)

In [50]:
exp

[2, 3]

In [51]:
mins

np.float64(0.13867953467198513)

In [52]:
maxs

np.float64(0.9076793994853366)

In [53]:
data

array([[[0.19415597, 0.41220146, 0.82525834, 0.1630201 ],
        [0.68669742, 0.65632551, 0.9912395 , 0.00110359],
        [0.60119661, 0.92870434, 0.29351993, 0.70496092]],

       [[0.41713171, 0.32231215, 0.83992331, 0.7242938 ],
        [0.89666796, 0.83728212, 0.92357801, 0.50269103],
        [0.95616948, 0.24889797, 0.77030681, 0.08384539]]])

In [54]:
data[0][0][0] = 700

In [55]:
data

array([[[7.00000000e+02, 4.12201464e-01, 8.25258344e-01, 1.63020102e-01],
        [6.86697423e-01, 6.56325512e-01, 9.91239496e-01, 1.10358778e-03],
        [6.01196607e-01, 9.28704337e-01, 2.93519931e-01, 7.04960916e-01]],

       [[4.17131713e-01, 3.22312153e-01, 8.39923312e-01, 7.24293804e-01],
        [8.96667960e-01, 8.37282124e-01, 9.23578014e-01, 5.02691032e-01],
        [9.56169475e-01, 2.48897967e-01, 7.70306808e-01, 8.38453901e-02]]])

In [56]:
data.sort()
data

array([[[1.63020102e-01, 4.12201464e-01, 8.25258344e-01, 7.00000000e+02],
        [1.10358778e-03, 6.56325512e-01, 6.86697423e-01, 9.91239496e-01],
        [2.93519931e-01, 6.01196607e-01, 7.04960916e-01, 9.28704337e-01]],

       [[3.22312153e-01, 4.17131713e-01, 7.24293804e-01, 8.39923312e-01],
        [5.02691032e-01, 8.37282124e-01, 8.96667960e-01, 9.23578014e-01],
        [8.38453901e-02, 2.48897967e-01, 7.70306808e-01, 9.56169475e-01]]])

In [57]:
print(data.shape)

(2, 3, 4)


In [59]:
data = data.reshape((2,2,-1))
data.shape

(2, 2, 6)

In [60]:
data

array([[[1.63020102e-01, 4.12201464e-01, 8.25258344e-01, 7.00000000e+02,
         1.10358778e-03, 6.56325512e-01],
        [6.86697423e-01, 9.91239496e-01, 2.93519931e-01, 6.01196607e-01,
         7.04960916e-01, 9.28704337e-01]],

       [[3.22312153e-01, 4.17131713e-01, 7.24293804e-01, 8.39923312e-01,
         5.02691032e-01, 8.37282124e-01],
        [8.96667960e-01, 9.23578014e-01, 8.38453901e-02, 2.48897967e-01,
         7.70306808e-01, 9.56169475e-01]]])

In [62]:
zeroes  = np.zeros((8))
print(zeroes)
zeroes = np.append(zeroes, [3,4])
print(zeroes)

[0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 3. 4.]


In [63]:
zeroes = np.insert(zeroes, 2,1)
print(zeroes)

[0. 0. 1. 0. 0. 0. 0. 0. 0. 3. 4.]


# 4. Delete

In [64]:
data

array([[[1.63020102e-01, 4.12201464e-01, 8.25258344e-01, 7.00000000e+02,
         1.10358778e-03, 6.56325512e-01],
        [6.86697423e-01, 9.91239496e-01, 2.93519931e-01, 6.01196607e-01,
         7.04960916e-01, 9.28704337e-01]],

       [[3.22312153e-01, 4.17131713e-01, 7.24293804e-01, 8.39923312e-01,
         5.02691032e-01, 8.37282124e-01],
        [8.96667960e-01, 9.23578014e-01, 8.38453901e-02, 2.48897967e-01,
         7.70306808e-01, 9.56169475e-01]]])

In [65]:
np.delete(data, 0, axis=1)

array([[[0.68669742, 0.9912395 , 0.29351993, 0.60119661, 0.70496092,
         0.92870434]],

       [[0.89666796, 0.92357801, 0.08384539, 0.24889797, 0.77030681,
         0.95616948]]])

In [68]:
np.save("New Array", data)

In [70]:
test = np.load("New Array.npy")

In [71]:
test

array([[[1.63020102e-01, 4.12201464e-01, 8.25258344e-01, 7.00000000e+02,
         1.10358778e-03, 6.56325512e-01],
        [6.86697423e-01, 9.91239496e-01, 2.93519931e-01, 6.01196607e-01,
         7.04960916e-01, 9.28704337e-01]],

       [[3.22312153e-01, 4.17131713e-01, 7.24293804e-01, 8.39923312e-01,
         5.02691032e-01, 8.37282124e-01],
        [8.96667960e-01, 9.23578014e-01, 8.38453901e-02, 2.48897967e-01,
         7.70306808e-01, 9.56169475e-01]]])